config/routes.rb
Spree::Core::Engine.routes.draw do
  
	namespace :admin do
		resources :bank_accounts
	end

  resources :orders do
    member do 
      post :confirm_payment
    end
  end
  
end

app/models/spree/bank_account.rb
module Spree
	class BankAccount < ActiveRecord::Base
		attr_accessible :payment_method_id, :bank_name, :bank_branch, :account_owner, :account_number
		validates :bank_name, :bank_branch, :account_owner, :account_number, :presence => true
		validates :account_number #, :numericality => { :only_integer => true }

		#belongs_to :payment_method
	end
end

app/models/spree/order_decorator.rb
module Spree
  Order.class_eval do
    attr_accessible :payment_confirmed
  end
end

app/models/spree/payment_method/bank_transfer.rb
module Spree
	class PaymentMethod::BankTransfer < PaymentMethod
		preference :twilio_sid, :string
		preference :twilio_token, :string
		preference :twilio_from, :string
		preference :twilio_to, :string

		attr_accessible :preferred_twilio_sid, :preferred_twilio_token, :preferred_twilio_from, :preferred_twilio_to

	  def actions
	  	%w{capture void}
	  end

	  def can_capture?(payment)
	  	['checkout', 'pending'].include?(payment.state)
	  end

	  def can_void?(payment)
	  	payment.state != 'void'
	  end

	  def capture(*args)
	  	ActiveMerchant::Billing::Response.new(true, "", {}, {})
	  end

	  def void(*args)
	  	ActiveMerchant::Billing::Response.new(true, "", {}, {})
	  end

	  def source_required?
	  	false
	  end
	end
end

app/controllers/spree/admin/bank_accounts_controller.rb
module Spree
  module Admin
    class BankAccountsController < ResourceController
    end
  end
end

app/controllers/spree/checkout_controller_decorator.rb
module Spree
	CheckoutController.class_eval do
		before_filter :load_bank_accounts

		private

		def load_bank_accounts
			@bank_accounts = BankAccount.all
		end
	end
end

app/controllers/spree/orders_controller_decorator.rb
module Spree
  OrdersController.class_eval do
    def confirm_payment
      @order = Order.find_by_number!(params[:id])
      
      twilio_sid = @order.payments.last.payment_method.preferred_twilio_sid
      twilio_token = @order.payments.last.payment_method.preferred_twilio_token
      twilio_from = @order.payments.last.payment_method.preferred_twilio_from
      twilio_to = @order.payments.last.payment_method.preferred_twilio_to

      sms_body = "#{params[:name]} has transferred #{Spree::Config.currency} " +
      "#{params[:amount]} to #{params[:bank_name]} for order #{@order.number}"

      require 'twilio-ruby'

      @client = Twilio::REST::Client.new twilio_sid, twilio_token

      @client.account.sms.messages.create(
        :from => twilio_from,
        :to => twilio_to,
        :body => sms_body
      )

      @order.payment_confirmed = true
      @order.save

      redirect_to @order
    end
  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
  BaseHelper.class_eval do
    def available_bank_accounts
      bank_accounts = BankAccount.all
    end
  end
end

app/views/spree/admin/bank_accounts/_form.html.erb
<div data-hook="admin_bank_account_form_fields">
  <div class="alpha twelve columns">
    <fieldset data-hook="bank_accounts" class=" no-border-bottom">
      <legend align="center"><%= t(:general_settings) %></legend>
      
      <div class="alpha six columns">
        <div data-hook="bank_name" class="field">
          <%= f.label :bank_name, t(:bank_name) %>
          <%= f.text_field :bank_name, :class => 'fullwidth' %>
        </div>
        <div data-hook="bank_branch" class="field">
          <%= f.label :bank_branch, t(:bank_branch) %>
          <%= f.text_field :bank_branch, :class => 'fullwidth' %>
        </div>
      </div>

      <div class="omega six columns">
        <div data-hook="account_owner" class="field">
          <%= f.label :account_owner, t(:account_owner) %>
          <%= f.text_field :account_owner, :class => 'fullwidth' %>
        </div>
        <div data-hook="account_number" class="field">
          <%= f.label :account_number, t(:account_number) %>
          <%= f.text_field :account_number, :class => 'fullwidth' %>
        </div>
      </div>
    </fieldset>
  </div>
  
  <div class="clear"></div>
</div>

app/views/spree/admin/bank_accounts/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:editing_bank_account) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_bank_accounts_list), spree.admin_bank_accounts_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @bank_account } %>

<%= form_for [:admin, @bank_account] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="clear"></div>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/bank_accounts/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:bank_accounts) %>
<% end %>

<% content_for :page_actions do %>
	<li>
	<%= button_link_to t(:new_bank_account), new_object_url, :icon => 'icon-plus' %>
	</li>
<% end %>

<% unless @bank_accounts.any? %>
  <div class="no-objects-found">
    <%= t(:no_results) %>
  </div>
<% else %>
  <table class="index">
    <colgroup>
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr data-hook="account_header">
        <th><%= t(:bank_name) %></th>
        <th><%= t(:bank_branch) %></th>
        <th><%= t(:account_owner) %></th>
        <th><%= t(:account_number) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @bank_accounts.each do |bank_account|%>
      <tr id="<%= spree_dom_id bank_account %>" data-hook="account_row" class="<%= cycle('odd', 'even')%>">
        <td><%=bank_account.bank_name %></td>
        <td><%=bank_account.bank_branch %></td>
        <td><%=bank_account.account_owner %></td>
        <td><%=bank_account.account_number %></td>
        <td class="actions">
          <%= link_to_edit bank_account, :no_text => true %>
          <%= link_to_delete bank_account, :no_text => true %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/bank_accounts/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:new_bank_account) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_bank_accounts_list), spree.admin_bank_accounts_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @bank_account } %>

<%= form_for [:admin, @bank_account] do |f| %>
  <fieldset class="no-border-top">
    
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div class="clear"></div>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>

app/views/spree/admin/payments/source_views/_banktransfer.html.erb
<div data-hook="bank_account" class="align-center">
  <h5> 은행: <span class="green"><%= @order.bank_account.bank_name %></span></h5>
	<h5> 계좌번호: <span class="green"><%= @order.bank_account.account_number %></span></h5>
	<h5> 예금주: <span class="green"><%= @order.bank_account.account_owner %></span></h5>
</div>

app/views/spree/checkout/payment/_banktransfer.html.erb
<% param_prefix = "payment_source[#{payment_method.id}]" %>

<p>
  <%= t(:please_make_your_payment_by_using_bank_transfer_to_one_of_the_following_banks) %>.
  <%= t(:please_continue_to_the_payment_confirmation_page_once_you_ve_made_your_payment) %>.
</p>

<table class="index">
  <colgroup>
    <col style="width: 5%">
    <col style="width: 20%">
    <col style="width: 25%">
    <col style="width: 25%">
    <col style="width: 35%">
  </colgroup>
  <thead>
    <tr data-hook="account_header">
      <th> </th>
      <th><%= t(:bank_name) %></th>
      <th><%= t(:bank_branch) %></th>
      <th><%= t(:account_owner) %></th>
      <th><%= t(:account_number) %></th>
    </tr>
  </thead>
  <tbody>
    <% @bank_accounts.each do |bank_account| %>
    <tr id="<%= bank_account %>" data-hook="account_row" class="<%= cycle('odd', 'even') %>">
      <td><%= bank_account.bank_name %></td>
      <td><%= bank_account.bank_branch %></td>
      <td><%= bank_account.account_owner %></td>
      <td><%= bank_account.account_number %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/orders/_payment_confirmation.html.erb
<% if @order.payment_confirmed %>
  <div class="notice flash">
    <%= t(:thank_you_for_confirming_your_payment_your_order_is_currently_being_processed) %>
  </div>
<% else %>
  <fieldset id="payment_confirmation" data-hook>
    <legend align="center"><%= t(:payment_confirmation) %></legend>
    <div id="@order" data-hook>
      <div class="row steps-data">
      
        <%= form_tag(confirm_payment_order_path, :method => "post", :id => "payment_confirmation_form") do %>
        <div class="columns alpha four">
          <p class="field" id=<%= "#{@order.id}name" %>>
            <%= label_tag :name, t(:name) %><span class="required">*</span><br />
            <%= text_field_tag :name, "", :class => 'required' %>
          </p>
        </div>

        <div class="columns alpha four">
          <p class="field" id=<%= "#{@order.id}amount" %>>
            <%= label_tag :amount, t(:amount) %><span class="required">*</span><br />
            <%= text_field_tag :amount, "", :class => 'required digits' %>
          </p>
        </div>

        <div class="columns alpha four">
          <p class="field" id=<%= "#{@order.id}bank_name" %>>
            <%= label_tag :bank_name, t(:bank_name) %><span class="required">*</span><br />
            <%= select_tag :bank_name, options_from_collection_for_select(available_bank_accounts, :bank_name, :bank_name) %>
          </p>
        </div>

        <div class="columns omega four">
          <div class="form-buttons" data-hook="buttons">
            <%= submit_tag Spree.t(:confirm), :class => 'continue button primary' %>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </fieldset>
  <script type="text/javascript">
    $(document).ready(function(){
      $("#payment_confirmation_form").validate();
      $("#payment_confirmation select").select2({
        width: "100%"
      });
    });
  </script>
  <style>
    #payment_confirmation legend {
      text-transform: uppercase;
      font-weight: bold;
      font-size: 14px;
      color: #00adee;
      padding: 5px;
      margin-left: 15px;
    }
    #payment_confirmation input[type="text"] {
      padding: 7px 5px;
    }
  </style>
<% end %>